In [60]:
import sys
myFunctionsFolder = "C:\\Users\\u5040252\\CloudStation\\Dropbox\\data Vincent\\Python\\myFunctions\\"
if not  myFunctionsFolder in sys.path:
    sys.path.append(myFunctionsFolder)
    


    
# from denoising import denoise_df, rolling_linear_reg, myround
from MyGraphs import *
import pandas as pd
import time
import os
import glob
from  collections import *
# import stats
import numpy as np

% matplotlib inline

In [78]:
def rolling_linear_reg( x, y,window=6):
        r = np.zeros(len(x))
        r[:] = np.NAN
        myrange = range(int(window/ 2), len(x) - int(window / 2))

        a = np.vstack([x, np.ones(len(x))]).T
        for i in myrange:
            r[i] = np.linalg.lstsq(a[i:i + window], y[i:i + window])[0][0]
        return r

In [79]:
def derive( df):
    for m in [44, 45, 47, 49]:
        df.loc[:, 'd' + str(m) + 'dt'] = rolling_linear_reg(df['time'], df['Mass' + str(m)])

    return df

In [80]:
datafolder = "C:\\Users\\U5040252\\Cloudstation\\Projects\\Mass_Spec_Data\\2016\\20160427"
pattern = '*_ph*.csv'  #date pattern. Examples: '2016', '201601', '20160331'

In [81]:
# for d in glob.glob(os.path.join(datafolder, pattern)):

d = os.path.join(datafolder, "20160427_ph78.csv")
df = pd.read_csv(d, encoding='ISO-8859-1')[['time','Mass44','Mass45','Mass47','Mass49','totalCO2',
                                             'd44dt','d45dt','d47dt','d49dt','dtotalCO2dt',
                                           'eventtype']]
    # 'd44dt','d45dt','d47dt','d49dt','dtotalCO2dt',

In [82]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,3761,3762,3763,3764,3765,3766,3767,3768,3769,3770
time,0.112667,0.225334,0.338001,0.450667,0.563334,0.676001,0.788668,1.014,1.10618,1.19837,...,379.239,379.34,379.442,379.543,379.644,379.746,379.847,379.949,380.05,380.152
Mass44,5.77672,5.77053,5.78499,5.78566,5.77443,5.78019,5.78263,5.78359,5.78191,5.7833,...,84.4192,84.4089,84.4192,84.431,84.4115,84.4096,84.4098,84.4189,84.424,84.4138
Mass45,0.081127,0.0658623,0.066033,0.0751156,0.0684349,0.0723856,0.0782657,0.0682774,0.0712043,0.0683167,...,1.00623,0.993513,1.0095,1.00329,0.999039,1.00353,1.00212,0.998593,1.00543,1.00622
Mass47,-0.000249379,-0.000262504,-0.00060376,0.00273004,-0.000853139,0.00393756,-0.000249379,0.0015619,-0.000853139,-0.0017194,...,0.00798013,0.00660198,0.00288755,0.00660198,0.0047382,0.00118127,0.00494821,0.00832139,0.00509258,0.00912203
Mass49,0.00557822,0.00334693,-5.25009e-05,0.000813763,0.00259879,0.00103689,0.000656261,0.00157503,0.00223129,0.00471195,...,0.00258567,0.000708762,0.00414757,0.00329443,0.00242816,0.00185066,0.000170628,0.00379319,0.00410819,0.00189003
totalCO2,5.89681,5.86638,5.87654,5.89087,5.87145,5.88086,5.8864,5.88658,5.88178,5.88184,...,85.7968,85.7676,85.7946,85.7988,85.7736,85.7715,85.7721,85.7877,85.7961,85.7912
d44dt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
d45dt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
d47dt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
d49dt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dtotalCO2dt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
eventtype,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
df2 = df[['time','Mass44','Mass45','Mass47','Mass49','totalCO2']].set_index(pd.to_datetime(df.time, unit='s'))

In [84]:
df2 = df2.resample('1s')

In [85]:
df3= derive(df2)

In [87]:
df3.to_csv(os.path.join(datafolder, "resampled_ph78.csv"))